baseline_file=./data/baseline.dat
report_dir=./reports
self_path=./integrity_monitor

watch=./sample_root/boot
watch=./sample_root/bin
watch=./sample_root/sbin
watch=./sample_root/usr/bin
watch=./sample_root/usr/sbin
watch=./sample_root/etc
watch=./sample_root/lib
watch=./sample_root/usr/lib
watch=./sample_root/root
watch=./sample_root/tmp
watch=./sample_root/dev/shm

exclude=./sample_root/proc
exclude=./sample_root/sys
exclude=./sample_root/run
